-------------------------------------------------------------------------------------------------------
-- Author       Cezar Lisboa
-- Created      25/05/2021
-- Purpose      Criado para assegurar todas as operações do CRUD do Sistema de Cadastro de Usuário - UVA
--              Prova de Teste Técnico
-------------------------------------------------------------------------------------------------------

IF EXISTS (SELECT * FROM sys.objects obj WHERE obj.object_id = OBJECT_ID(N'[dbo].[SP_CAD_USUARIO_UVA]'))
	DROP PROCEDURE [dbo].[SP_CAD_USUARIO_UVA]
GO

CREATE PROCEDURE [dbo].[SP_CAD_USUARIO_UVA]
	@OPC_OPERACAO			CHAR(3) = NULL
   ,@NUM_OPERACAO			TINYINT = NULL
   ,@COD_USUARIO			BIGINT = NULL
   ,@NOME_USUARIO			VARCHAR(255) = NULL
   ,@CPF_USUARIO			CHAR(11) = NULL
   ,@CPF_USUARIO_PESQUISA	VARCHAR(11) = NULL
   ,@TELEFONE_USUARIO		VARCHAR(15) = NULL
   ,@EMAIL_USUARIO			VARCHAR(255) = NULL
   ,@ATIVO					BIT = NULL
   ,@DATA_CRIACAO_INICIO	DATETIME = NULL
   ,@DATA_CRIACAO_FIM		DATETIME = NULL
AS
IF @OPC_OPERACAO = 'SEL'
	BEGIN
		IF @NUM_OPERACAO = 1 -- CAPTURA TODOS OS USUÁRIOS
			BEGIN
				SELECT
					UVA.COD_USUARIO		 AS CodigoUsuario,
					UVA.NOME_USUARIO	 AS NomeUsuario,
					UVA.CPF_USUARIO		 AS CPFUsuario,
					UVA.TELEFONE_USUARIO AS TelefoneUsuario,
					UVA.EMAIL_USUARIO	 AS EmailUsuario,
					UVA.DATA_CRIACAO	 AS DataCriacao,
					UVA.ATIVO			 AS Ativo 
				FROM 
					TBL_CAD_USUARIO_UVA UVA
				ORDER BY 
					UVA.DATA_CRIACAO DESC
			END

		IF @NUM_OPERACAO = 2 -- CAPTURA O USUÁRIO PELO CÓDIGO
			BEGIN
				SELECT
					UVA.COD_USUARIO		 AS CodigoUsuario,
					UVA.NOME_USUARIO	 AS NomeUsuario,
					UVA.CPF_USUARIO		 AS CPFUsuario,
					UVA.TELEFONE_USUARIO AS TelefoneUsuario,
					UVA.EMAIL_USUARIO	 AS EmailUsuario,
					UVA.DATA_CRIACAO	 AS DataCriacao,
					UVA.ATIVO			 AS Ativo 
				FROM 
					TBL_CAD_USUARIO_UVA UVA
				WHERE
					UVA.COD_USUARIO = @COD_USUARIO;
			END

		IF @NUM_OPERACAO = 3 -- FILTRO DE USUÁRIOS
			BEGIN
				SELECT
					UVA.COD_USUARIO		 AS CodigoUsuario,
					UVA.NOME_USUARIO	 AS NomeUsuario,
					UVA.CPF_USUARIO		 AS CPFUsuario,
					UVA.TELEFONE_USUARIO AS TelefoneUsuario,
					UVA.EMAIL_USUARIO	 AS EmailUsuario,
					UVA.DATA_CRIACAO	 AS DataCriacao,
					UVA.ATIVO			 AS Ativo 
				FROM 
					TBL_CAD_USUARIO_UVA UVA
				WHERE 
					(@NOME_USUARIO IS NULL OR @NOME_USUARIO = '' OR LOWER(UVA.NOME_USUARIO) LIKE '%' + LOWER(@NOME_USUARIO) + '%')
				AND
					(@EMAIL_USUARIO IS NULL OR @EMAIL_USUARIO = '' OR LOWER(UVA.EMAIL_USUARIO) LIKE '%' + LOWER(@EMAIL_USUARIO) + '%')
				AND
					(@CPF_USUARIO_PESQUISA IS NULL OR @CPF_USUARIO_PESQUISA = '' OR UVA.CPF_USUARIO LIKE '%' + @CPF_USUARIO_PESQUISA + '%')
				AND
					((@DATA_CRIACAO_INICIO IS NULL AND @DATA_CRIACAO_FIM IS NULL)
				OR 
					CAST(UVA.DATA_CRIACAO AS DATE) BETWEEN CAST(@DATA_CRIACAO_INICIO AS DATE) AND CAST(@DATA_CRIACAO_FIM AS DATE))		
			END
	END

IF @OPC_OPERACAO = 'INS'
	BEGIN
		IF @NUM_OPERACAO = 1 -- INSERE UM NOVO USUÁRIO
			BEGIN
				INSERT TBL_CAD_USUARIO_UVA (
					NOME_USUARIO,
					CPF_USUARIO,
					TELEFONE_USUARIO,
					EMAIL_USUARIO,
					ATIVO)
				VALUES (
					@NOME_USUARIO,
					@CPF_USUARIO,
					@TELEFONE_USUARIO,
					@EMAIL_USUARIO,
					@ATIVO)
			END
	END

IF @OPC_OPERACAO = 'UPD'
	BEGIN
		IF @NUM_OPERACAO = 1 -- ATUALIZA O USUÁRIO INFORMADO
			BEGIN
				UPDATE 
					TBL_CAD_USUARIO_UVA 
				SET
					NOME_USUARIO = @NOME_USUARIO,
					CPF_USUARIO = @CPF_USUARIO,
					TELEFONE_USUARIO = @TELEFONE_USUARIO,
					EMAIL_USUARIO = @EMAIL_USUARIO,
					ATIVO = @ATIVO
				WHERE 
					COD_USUARIO = @COD_USUARIO;
			END
	END

IF @OPC_OPERACAO = 'DEL'
	BEGIN
		IF @NUM_OPERACAO = 1 -- DELETA O USUÁRIO INFORMADO
			BEGIN
				DELETE
					TBL_CAD_USUARIO_UVA
				WHERE
					COD_USUARIO = @COD_USUARIO;
			END
	END