-- VERIFICAR A LOCALIZAÇÃO DO .MDF NO DIRETÓRIO LOCAL
USE [C:\PROJETO-TESTE-UVA\DATA-BASE\DBCADUVA.MDF]
GO

CREATE TABLE dbo.TBL_CAD_USUARIO_UVA (
	COD_USUARIO BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NOME_USUARIO VARCHAR(255) NULL,
	CPF_USUARIO CHAR(11) NULL,
	TELEFONE_USUARIO VARCHAR(15) NULL,
	EMAIL_USUARIO VARCHAR(255) NULL,
	DATA_CRIACAO DATETIME DEFAULT GETDATE() NULL,
	ATIVO BIT NULL
);